@extends('layouts.register')
@section('style')
    <style>
        @include('css.HeaderCss');
        @include('css.LoginCss');
    </style>
@endsection
@section('script')
    @include('js.HeaderJs');
@endsection
